development: 
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: tweetabitcoin_development
  pool: 5
  username: johncapecelatro
  password: 

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: tweetabitcoin_test
  pool: 5
  username: johncapecelatro
  password:

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: tweetabitcoin_production
  pool: 5
  username: johncapecelatro
  password:
